---
- name: Service playbook
  hosts: aws_ec2
  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist

    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent

  roles:
    - oabo/installdocker/roles/installdocker
    - installdockercompose
  remote_user: ubuntu
  become: yes
  post_tasks:

    - name: Add user to docker group
      user:
        name: "{{ansible_user}}"
        group: docker

    - name: Clone a repository
      git:
        repo: "https://github.com/bhavenger/skillbox-diploma.git"
        dest: "/usr/local/skillbox-diploma"
        clone: yes
        update: yes

    - name: Run tests
      command: ./run-tests.sh
      args:
        chdir: "/usr/local/skillbox-diploma"

    - name: Compose
      command: /usr/local/bin/docker-compose build
      args:
        chdir: "/usr/local/skillbox-diploma"

    - name: Copy unit to host
      copy:
        src: ../instahelper.service
        dest: /etc/systemd/system/instahelper.service
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Enable service
      systemd:
        name: instahelper.service
        state: started
        enabled: yes




